### ISSUE TITLE
Crash reported by Butch

### ISSUE THREAD

**Issue by JohnySeven** [JohnySeven/SKipper#7]
@ba58smith Started demo, when to Home, then Settings, and whether or not I change a setting, it crashes when I try to go back to Home. This happens even with a brand new set of SKipper files, and without putting the ui.json from your boat in place. Why is it referring to D:\MyProjects\Skipper\etc? I don't have a D: drive and I don't have a MyProjects folder.

`System.NullReferenceException: Object reference not set to an instance of an object.
   at Skipper.Services.AppConfiguration.Save(ConfigurationSection configuration) in D:\MyProjects\Skipper\Skipper\Services\AppConfiguration.cs:line 84
   at Skipper.ViewModels.SettingsViewModel.SaveSettings() in D:\MyProjects\Skipper\Skipper\ViewModels\SettingsViewModel.cs:line 30
   at Skipper.Views.SettingsPage.OnDisappearing() in D:\MyProjects\Skipper\Skipper\Views\SettingsPage.axaml.cs:line 27
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at Avalonia.Threading.SendOrPostCallbackDispatcherOperation.InvokeCore() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 412
   at Avalonia.Threading.DispatcherOperation.Execute() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 268
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job) in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 126
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 181
   at Avalonia.Threading.Dispatcher.Signaled() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 134`

Same thing happens if I try to toggle the "Show at startup" icon for any page.

**Comment by JohnySeven** [comment]
I think I've fixed the issue.
